# Generated by Django 3.2.5 on 2022-06-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=64)),
                ('item_category', models.CharField(max_length=64)),
                ('item_owner', models.CharField(max_length=64)),
                ('item_bid_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('item_bid_count', models.IntegerField()),
                ('item_image_url', models.URLField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
    ]
