# Generated by Django 3.2.5 on 2022-06-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='item_category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.PROTECT, to='auctions.category'),
        ),
    ]
