# Generated by Django 3.2.5 on 2022-06-06 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctions_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=64)),
                ('item_bid_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('item_bid_count', models.IntegerField()),
                ('item_image_url', models.URLField(max_length=256)),
                ('item_category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.PROTECT, to='auctions.category')),
                ('item_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Auctions',
        ),
    ]
