# Generated by Django 3.2.5 on 2022-06-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20220606_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='item_description',
            field=models.CharField(default='item_description_placeholder', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='item_starting_bid',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=9),
            preserve_default=False,
        ),
    ]
