# Generated by Django 3.2.5 on 2022-06-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20220606_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='item_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
