# Generated by Django 3.2.5 on 2022-06-10 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_item_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='users_watching',
            field=models.ManyToManyField(blank=True, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
