# Generated by Django 3.2.5 on 2022-08-01 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geocache', '0002_discussionboard_geocache'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionboard',
            name='comment_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='discussionboard',
            name='comment_poster',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='geocache.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discussionboard',
            name='comment_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='discussionboard',
            name='geocache',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='geocache.geocache'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discussionboard',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geocache',
            name='expiry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geocache',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geocache',
            name='founder',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='founder', to=settings.AUTH_USER_MODEL),
        ),
    ]
