# Generated by Django 3.2.5 on 2022-08-01 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocache', '0003_auto_20220801_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geocache',
            name='founder',
        ),
        migrations.AddField(
            model_name='geocache',
            name='founder',
            field=models.ManyToManyField(blank=True, related_name='founder', to=settings.AUTH_USER_MODEL),
        ),
    ]
