# Generated by Django 3.2.5 on 2022-08-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocache', '0006_pointofinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocache',
            name='hint',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
