# Generated by Django 3.2.5 on 2022-08-12 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocache', '0007_geocache_hint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointOfInterest',
        ),
        migrations.RemoveField(
            model_name='geocache',
            name='expiry_time',
        ),
        migrations.RemoveField(
            model_name='geocache',
            name='position',
        ),
    ]
