# Generated by Django 3.2.5 on 2022-08-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocache', '0008_auto_20220812_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocache',
            name='title',
            field=models.CharField(default='PLACEHOLDER TITLE', max_length=255),
            preserve_default=False,
        ),
    ]
